-- 1. Movie Stars
-- Write a query to retrieve the first and last names of all actors who appeared in the movie "AGENT TRUMAN".
USE sakila;

SELECT a.first_name, a.last_name
FROM actor AS a
INNER JOIN film_actor AS fa ON a.actor_id = fa.actor_id
INNER JOIN film AS f ON fa.film_id = f.film_id
WHERE title = 'AGENT TRUMAN';

-- 2. Target Audience
-- The marketing department needs to contact users who have shown interest in a specific film. 
-- Extract the first name, last name, and email address of all customers who have rented the movie "ACADEMY DINOSAUR".
SELECT c.first_name, c.last_name, c.email
FROM customer AS c
INNER JOIN rental AS r ON c.customer_id = r.customer_id
INNER JOIN inventory AS i ON r.inventory_id = i.inventory_id
INNER JOIN film AS f ON i.film_id = f.film_id
WHERE title = 'ACADEMY DINOSAUR';

-- 3. * Revenue by Category
-- Which film categories generate the most profit? Write a query that joins the necessary tables to display the category_name 
-- and the total revenue generated by films in that category. Sort the results from highest revenue to lowest.
SELECT c.`name` AS category_name, SUM(p.amount) AS sum_revenue FROM category AS C
INNER JOIN film_category AS fc ON c.category_id = fc.category_id
INNER JOIN film AS f ON fc.film_id = f.film_id
INNER JOIN inventory AS i ON f.film_id = i.film_id
INNER JOIN rental AS r ON i.inventory_id = r.inventory_id
INNER JOIN payment AS p ON r.rental_id = p.rental_id
GROUP BY c.`name`
ORDER BY sum_revenue DESC;

-- 4. Numbering the Longest Films
-- Write a query that displays the title and length of every film in the film table. Use a window function to assign a sequential 
-- row number (ROW_NUMBER()) to each film, sorting them by length from longest to shortest. 
-- (Note: You do not need to use PARTITION BY inside the OVER() clause).
SELECT title, length, 
ROW_NUMBER() OVER (ORDER BY length DESC) AS row_id
FROM sakila.film
ORDER BY length DESC;

-- 5. Comparison with the Global Average
-- We want to see how the replacement cost (replacement_cost) of each film compares to the overall average. 
-- Display the film title and its replacement_cost. Add a third column using a window function that displays the 
-- average replacement cost of all films in the database side-by-side. (Hint: Use the AVG() function with an empty OVER() clause).
SELECT title, replacement_cost,
AVG(replacement_cost) OVER() AS avg_replacement_cost
FROM sakila.film;
